development:
  adapter: postgresql
  encoding: UTF-8
  host: localhost
  database: adztream_adserver_development
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: UTF-8
  host: localhost
  database: adztream_adserver_test
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
